name: Build and Deploy to Github Pages

on:
  push:
    branches:
      - master 
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: EdricChan03/action-build-deploy-ghpages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
